### PR TITLE
Task/COOKS-264: Add 2 default checked map layers.

### PR DESCRIPTION
**Pull request by duckonomy**
## Overview: ##
Set Child and Youth Services and Cook Children's Locations on by default.

## Related Jira tickets: ##

* [COOKS-264](https://jira.tacc.utexas.edu/browse/COOKS-264)

## Summary of Changes: ##
Changed `MainMap.js`.

## Testing Steps: ##
1. Ensure that Child and Youth Services and Cook Children's Locations are on by default.

## Notes: ##
I wasn't sure if I should check directly with the `NAICS_CODE` or through the resource description (requires extra check).

### CODE REVIEW

**Review by taoteg — CHANGES_REQUESTED** [review]
This behaves as expected on initial load.  However, as soon as you select any region and the map zooms, it reapplies all the map resource layers and displays them in the clustering. 

It would be my assumption that we would _not_ add any additional resource layers unless the user explicitly selects them in the drop down for the map after having selected a region to focus on.

Also, when the globe icon is clicked to refresh the view, it removes _all_ layers, it should restore the default state.

When the Map view is reset after either a region selection or zoom reset event, ensure that only the default two layers are being displayed on the map.

Might need to add a component property to track the default resource layers and pass them into the map component for proper handling in every case, rather than just at the marker clustering level.

**Comment by taoteg** [comment]
Examples of the inital load state, after region selection and after globe reset  click.

Screen Shot 2022-05-24 at 3 52 34 PM

Screen Shot 2022-05-24 at 3 52 47 PM

Screen Shot 2022-05-24 at 3 53 04 PM

**Review by taoteg — COMMENTED** [review]
Looks great!

**Review by taoteg — APPROVED** [review]
Looks Great!

**Review by nathanfranklin — APPROVED** [review]
LGTM 👍

**Pull request merged**
