### PR TITLE
COOKS-204: Update to color scheme sent by Cooks

### PR DESCRIPTION
**Pull request by taoteg**
## Overview: ##

Changed the colors for the map component. 

## Related Jira tickets: ##

* [COOKS-204](https://jira.tacc.utexas.edu/browse/COOKS-204)

## Summary of Changes: ##

- Added a new stylesheet to the map. 
- Updated the plot colors based on cooks color palette.

## Testing Steps: ##

1. Build and run project.

## UI Photos:

Screen Shot 2022-04-12 at 6 15 43 PM

Screen Shot 2022-04-12 at 6 16 03 PM

Screen Shot 2022-04-12 at 6 16 34 PM

Screen Shot 2022-04-12 at 6 16 56 PM

Screen Shot 2022-04-12 at 6 17 17 PM

Screen Shot 2022-04-12 at 6 17 52 PM

Screen Shot 2022-04-12 at 6 18 38 PM

EDIT: Circle Marker Colors Updated

Screen Shot 2022-04-13 at 8 18 26 AM

### CODE REVIEW

**Review by wesleyboar — COMMENTED** [review]
**Eyeball Review**

Based on just the screenshots[^1], the circled counts are still green/yellow/orange instead of shades of gray.

<details><summary>Comparison</summary>

| Expected | Actual |
| - | - |
| COOKS-204 v0-1 Demo Perc | Screen Shot 2022-04-12 at 6 16 56 PM |

</details>

The code that should change them is [under `/* circles */` at the bottom of `ProtxColors.css`](https://github.com/TACC/protx/blob/ffa4c94/client/src/components/ProTx/components/maps/ProtxColors.css#L117-L133). Perhaps the difference is because the screenshots are just old or the markup has changed.

[^1]: I haven't set up a local environment to test.

**Comment by wesleyboar** [comment]
I see my CSS used directly, which is cool, but I think also means we're painting over the wall instead of changing the source of truth colors. I tried to do this in my branch, but could never test it. I have [fixed the link to my branch](https://github.com/TACC/protx/compare/main...wesleyboar:task/COOKS-204-new-colors). Also, I know y'all are under the gun, so I defer to y'alls method.

**Comment by taoteg** [comment]
> **Eyeball Review**
> 
> Based on just the screenshots[1](#user-content-fn-1-39124b44c68e12e0683c38a6134fad6f), the circled counts are still green/yellow/orange instead of shades of gray.
> 
> Comparison
> The code that should change them is [under `/* circles */` at the bottom of `ProtxColors.css`](https://github.com/TACC/protx/blob/ffa4c94/client/src/components/ProTx/components/maps/ProtxColors.css#L117-L133). Perhaps the difference is because the screenshots are just old or the markup has changed.

Good catch! Those selectors may require `!override` values because they are from a 3rd party plugin that manages its own styles during the marker clustering.

**Comment by wesleyboar** [comment]
Ah, makes sense.[^1]

[^1]: Those third-party styles may be loaded _after_ TACC styles, so what worked for me via Inspector (which is applied after everything) doesn't work in live portal.

**Comment by wesleyboar** [comment]
Okay. 👍

<sub>I don't intend to force a rework now, cuz I know about the urgency of this sprint's changes, but [there may be a way to change the colors at the source](https://github.com/TACC/protx/pull/102#issuecomment-1097426423).</sub>

**Comment by taoteg** [comment]
Ahh, I see what you were thinking, and that should be workable after a bit more dev is done, but we actually stopped using that centralized colors file because we moved the rendering to the server side. Right now the colors are hardcoded into each plots python file. 
I have a task this sprint to standardize/normalize this color setup and use a proper key mapping:
https://jira.tacc.utexas.edu/browse/COOKS-228

**Review by wesleyboar — APPROVED** [review]
I have re-reviewed, and am happy to hear there is a plan for color management.

I approve, but I suggest someone else _with the ability to test_ takes a look.

**Pull request merged**
